global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'champion-model'
    static_configs:
      - targets: ['champion-model:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'challenger-models'
    static_configs:
      - targets: ['shadow-challenger:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: '/metrics'
    scrape_interval: 60s

  - job_name: 'mlops-scheduler'
    static_configs:
      - targets: ['mlops-scheduler:8000']
    metrics_path: '/metrics'
    scrape_interval: 60s
