evaluation:
  improvement_threshold: 0.01
  metrics:
  - accuracy
  - precision
  - recall
  - f1_score
mlflow:
  experiment_name: simple_champion_challenger
  tracking_uri: http://localhost:5001
training:
  models:
    logistic_regression:
      max_iter: 1000
    random_forest:
      max_depth: 10
      n_estimators: 100
  random_state: 42
  test_size: 0.2
